[package]
org = "ballerinax"
name = "solace.smf"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-solace.smf"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.10"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "solace-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/solace.smf-native-0.1.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "com.solacesystems"
artifactId = "sol-jcsmp"
version = "10.29.0"
path = "./lib/sol-jcsmp-10.29.0.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "@netty.version@"
path = "./lib/netty-common-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "@netty.version@"
path = "./lib/netty-buffer-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "@netty.version@"
path = "./lib/netty-transport-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "@netty.version@"
path = "./lib/netty-resolver-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "@netty.version@"
path = "./lib/netty-handler-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "@netty.version@"
path = "./lib/netty-codec-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "@netty.version@"
path = "./lib/netty-codec-http-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "@netty.version@"
path = "./lib/netty-handler-proxy-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-epoll"
version = "@netty.version@"
path = "./lib/netty-transport-native-epoll-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-epoll"
version = "@netty.version@"
path = "./lib/netty-transport-classes-epoll-@netty.version@.jar"

[[platform.java21.dependency]]
path = "./lib/netty-transport-native-epoll-@netty.version@-linux-x86_64.jar"

[[platform.java21.dependency]]
path = "./lib/netty-transport-native-epoll-@netty.version@-linux-aarch_64.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "@netty.version@"
path = "./lib/netty-transport-native-unix-common-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-kqueue"
version = "@netty.version@"
path = "./lib/netty-transport-native-kqueue-@netty.version@.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-kqueue"
version = "@netty.version@"
path = "./lib/netty-transport-classes-kqueue-@netty.version@.jar"
