[package]
org = "ballerinax"
name = "solace.smf"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-solace.smf"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.10"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "solace-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/solace.smf-native-0.1.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "com.solacesystems"
artifactId = "sol-jcsmp"
version = "10.29.0"
path = "./lib/sol-jcsmp-10.29.0.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.2.7.Final"
path = "./lib/netty-common-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.2.7.Final"
path = "./lib/netty-transport-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.2.7.Final"
path = "./lib/netty-handler-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.2.7.Final"
path = "./lib/netty-resolver-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.2.7.Final"
path = "./lib/netty-buffer-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.2.7.Final"
path = "./lib/netty-codec-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "4.2.7.Final"
path = "./lib/netty-codec-http-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "4.2.7.Final"
path = "./lib/netty-handler-proxy-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-epoll"
version = "4.2.7.Final"
path = "./lib/netty-transport-native-epoll-4.2.7.Final.jar"

[[platform.java21.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-epoll"
version = "4.2.7.Final"
path = "./lib/netty-transport-classes-epoll-4.2.7.Final.jar"

