name: Daily build

on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  call_workflow:
    name: Run Daily Build Workflow
    if: ${{ github.repository_owner == 'xlibb' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/daily-build-connector-template.yml@main
    secrets: inherit
    with:
      repo-name: module-solace
      additional-build-flags: "-x test"
      additional-test-flags: "-x test"
