name: Publish Release

on:
  workflow_dispatch:

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'xlibb' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/release-package-connector-template.yml@main
    secrets: inherit
    with:
      package-name: solace
      package-org: xlibb
