name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron:  "30 20 * * *"

jobs:
  call_workflow:
    name: Run Trivy Scan Workflow
    if: ${{ github.repository_owner == 'xlibb' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/trivy-scan-template.yml@main
    secrets: inherit
    with:
      additional-build-flags: "-x test"
